### ISSUE TITLE
recursive module is not getting cloned

### ISSUE THREAD

**Issue by paibhushang** [f5devcentral/terraform-xc-aws-ce#1]
The "modules" submodule is not correctly referenced.

git clone throws error:
fatal: remote error: upload-pack: not our ref e3b7750ee07b6f7ab7afe18d9f0df84a03756618
fatal: Fetched in submodule path 'modules', but it did not contain e3b7750ee07b6f7ab7afe18d9f0df84a03756618. Direct fetching of that commit failed.

**Comment by cklewar** [comment]
commit to latest fixed issue.
