### ISSUE TITLE
The AWS security group rules array/list in the examples section are empty.

### ISSUE THREAD

**Issue by Nikoolayy1** [f5devcentral/terraform-xc-aws-ce#5]
The AWS security group rules in the examples are empty. Can there be example how the provider will add this security groups ?

![image](https://github.com/f5devcentral/terraform-xc-aws-ce/assets/23706402/26001423-6d8e-4f66-8e72-72229915ae52)

**Comment by cklewar** [comment]
@Nikoolayy1 example has been added to chapter  `Feature specific examples` at: https://github.com/f5devcentral/terraform-xc-aws-ce?tab=readme-ov-file#feature-specific-examples
