### ISSUE TITLE
Getting multiple 400 errors when using manual mode to deploy CE's in aws

### ISSUE THREAD

**Issue by Nettas** [f5devcentral/terraform-xc-aws-ce#6]
Getting multiple 400 errors when using manual mode to deploy CE's in aws.  Using https://github.com/f5devcentral/terraform-xc-aws-ce/tree/main and trying to deploy the three_node_cluster_multi_nic_new_vpc_new_subnet option:

Error outputs:
Error: error creating SecuremeshSite: Creating object: Unsuccessful POST at URL https://visa.console.ves.volterra.io/api/public/namespaces/system/securemesh_sites, status code 400, body <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd>
│ <html xmlns=http://www.w3.org/1999/xhtml class="">
│ 
│ <head>
│     <meta charset="utf-8">
│     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
│     <meta name="robots" content="noindex, nofollow">
│     <meta name="viewport" content="width=device-width,initial-scale=1">
│ 
│     <title>        We&#39;re sorry...
│ </title>
│     <link rel="shortcut icon" href="/auth/resources/ks7v1/login/volterra/img/favicon.ico?v=2" />
│             <link href="/auth/resources/ks7v1/login/volterra/third-party-lib/zocial-1.3.0/zocial.min.css" rel="stylesheet" />
│             <link href="/auth/resources/ks7v1/login/volterra/dist/main.css?v7.0.15" rel="stylesheet" />
│     <style>
│         :root {
│             --spinner: url('data:image/svg+xml;base64,PHN2ZyBjbGFzcz0ic3BpbiIgd2lkdGg9IjE4IiBoZWlnaHQ9IjE4IiB2aWV3Qm94PSIwIDAgMTggMTgiIGZpbGw9IiNmZmYiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPHBhdGggaWQ9InNlZ21lbnQiIGQ9Ik0xNS43NSA5QTYuNzUgNi43NSAwIDExOSAyLjI1YS43NS43NSAwIDAwMC0xLjVBOC4yNSA4LjI1IDAgMTAxNy4yNSA5YS43NS43NSAwIDAwLTEuNSAweiI+PC9wYXRoPgo8L3N2Zz4=');
│         }
│     </style>
│     <script type="text/javascript">
│         function injectTracker(src, async, crossorigin) {
│             // tora browser should not have any trackers injected
│             if (!navigator.userAgent.endsWith('TORA-RUNNER')) {
│                 var scriptElem = document.createElement('script');
│                 scriptElem.type= 'text/javascript';
│                 scriptElem.src = src;
│                 if (async) {
│                     scriptElem.async = true;
│                 }
│                 if (crossorigin) {
│                     scriptElem.setAttribute('crossorigin', '');
│                 }
│                 document.head.appendChild(scriptElem);
│             }
│         }
│     </script>
│     <script type="text/javascript">
│         var vesStellarBaseUrl = 'console.ves.volterra.io';
│     </script>
│             <script src="/auth/resources/ks7v1/login/volterra/dist/main.js?v7.0.9" type="text/javascript"></script>
│ </head>
│ 
│ <body class=" template">
│     <div id="kc-container" class="">
│         
│ 
│               <div class="d-flex page-container">
│               <div id="kc-error-message" class="d-flex error-page-container">
│                               <div class="card error text-center">
│                                       <div class="card-header">
│                                               <div class="message-icon">
│                                                       <i class="icon vsi-md"><i class="vsi-error-stop"></i></i>
│                                               </div>
│                                               error
│                                       </div>
│                                       <div class="card-body">
│                                   <p class="instruction">Invalid parameter: redirect_uri</p>
│ 
│                                       <a id="backToApplication"
│                                                          href="#"
│                                                          class="btn btn-primary btn-block btn-lg">
│                                                         Try again
│                                                 </a>
│                                       </div>
│                               </div>
│                       </div>
│               </div>
│ 
│ 
│         <div class="privacy-footer">
│             <span class="copyright-text">© <span id="privacy-year">2022</span>  F5, Inc. All Rights Reserved.</span>
│             <span class="seperator-dot"></span>
│             <a class="privacy-link" href=https://www.f5.com/company/policies target="_blank" rel="noreferrer noopener">
│                 Policies
│             </a>
│              <span class="seperator-dot"></span>
│             <a class="privacy-link" href=https://www.f5.com/company/policies/trademarks target="_blank" rel="noreferrer noopener">
│                 Trademarks
│             </a>
│             <span class="seperator-dot"></span>
│             <a class="privacy-link" href=https://www.f5.com/company/policies/F5-California-privacy-summary target="_blank" rel="noreferrer noopener">
│                 F5 CA Privacy Summary
│             </a>
│             <span class="seperator-dot"></span>
│             <a class="privacy-link" href=https://www.f5.com/company/policies/privacy-notice#no-sell target="_blank" rel="noreferrer noopener">
│                 Do Not Sell My Personal Information
│             </a>
│         </div>
│     </div>
│     
│ </body>
│ </html>
│ 
│ 
│   with module.f5xc_aws_cloud_ce_three_node_multi_nic_new_vpc_new_subnet.module.secure_mesh_site[0].volterra_securemesh_site.secure_mesh_site,
│   on ../../modules/f5xc/secure-mesh-site/main.tf line 1, in resource "volterra_securemesh_site" "secure_mesh_site":
│    1: resource "volterra_securemesh_site" "secure_mesh_site" {
│ 
╵
╷
│ Error: error creating Token: Creating object: Unsuccessful POST at URL https://visa.console.ves.volterra.io/api/public/namespaces/system/tokens, status code 400, body <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd>
│ <html xmlns=http://www.w3.org/1999/xhtml class="">
│ 
│ <head>
│     <meta charset="utf-8">
│     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
│     <meta name="robots" content="noindex, nofollow">
│     <meta name="viewport" content="width=device-width,initial-scale=1">
│ 
│     <title>        We&#39;re sorry...
│ </title>
│     <link rel="shortcut icon" href="/auth/resources/ks7v1/login/volterra/img/favicon.ico?v=2" />
│             <link href="/auth/resources/ks7v1/login/volterra/third-party-lib/zocial-1.3.0/zocial.min.css" rel="stylesheet" />
│             <link href="/auth/resources/ks7v1/login/volterra/dist/main.css?v7.0.15" rel="stylesheet" />
│     <style>
│         :root {
│             --spinner: url('data:image/svg+xml;base64,PHN2ZyBjbGFzcz0ic3BpbiIgd2lkdGg9IjE4IiBoZWlnaHQ9IjE4IiB2aWV3Qm94PSIwIDAgMTggMTgiIGZpbGw9IiNmZmYiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPHBhdGggaWQ9InNlZ21lbnQiIGQ9Ik0xNS43NSA5QTYuNzUgNi43NSAwIDExOSAyLjI1YS43NS43NSAwIDAwMC0xLjVBOC4yNSA4LjI1IDAgMTAxNy4yNSA5YS43NS43NSAwIDAwLTEuNSAweiI+PC9wYXRoPgo8L3N2Zz4=');
│         }
│     </style>
│     <script type="text/javascript">
│         function injectTracker(src, async, crossorigin) {
│             // tora browser should not have any trackers injected
│             if (!navigator.userAgent.endsWith('TORA-RUNNER')) {
│                 var scriptElem = document.createElement('script');
│                 scriptElem.type= 'text/javascript';
│                 scriptElem.src = src;
│                 if (async) {
│                     scriptElem.async = true;
│                 }
│                 if (crossorigin) {
│                     scriptElem.setAttribute('crossorigin', '');
│                 }
│                 document.head.appendChild(scriptElem);
│             }
│         }
│     </script>
│     <script type="text/javascript">
│         var vesStellarBaseUrl = 'console.ves.volterra.io';
│     </script>
│             <script src="/auth/resources/ks7v1/login/volterra/dist/main.js?v7.0.9" type="text/javascript"></script>
│ </head>
│ 
│ <body class=" template">
│     <div id="kc-container" class="">
│         
│ 
│               <div class="d-flex page-container">
│               <div id="kc-error-message" class="d-flex error-page-container">
│                               <div class="card error text-center">
│                                       <div class="card-header">
│                                               <div class="message-icon">
│                                                       <i class="icon vsi-md"><i class="vsi-error-stop"></i></i>
│                                               </div>
│                                               error
│                                       </div>
│                                       <div class="card-body">
│                                   <p class="instruction">Invalid parameter: redirect_uri</p>
│ 
│                                       <a id="backToApplication"
│                                                          href="#"
│                                                          class="btn btn-primary btn-block btn-lg">
│                                                         Try again
│                                                 </a>
│                                       </div>
│                               </div>
│                       </div>
│               </div>
│ 
│ 
│         <div class="privacy-footer">
│             <span class="copyright-text">© <span id="privacy-year">2022</span>  F5, Inc. All Rights Reserved.</span>
│             <span class="seperator-dot"></span>
│             <a class="privacy-link" href=https://www.f5.com/company/policies target="_blank" rel="noreferrer noopener">
│                 Policies
│             </a>
│              <span class="seperator-dot"></span>
│             <a class="privacy-link" href=https://www.f5.com/company/policies/trademarks target="_blank" rel="noreferrer noopener">
│                 Trademarks
│             </a>
│             <span class="seperator-dot"></span>
│             <a class="privacy-link" href=https://www.f5.com/company/policies/F5-California-privacy-summary target="_blank" rel="noreferrer noopener">
│                 F5 CA Privacy Summary
│             </a>
│             <span class="seperator-dot"></span>
│             <a class="privacy-link" href=https://www.f5.com/company/policies/privacy-notice#no-sell target="_blank" rel="noreferrer noopener">
│                 Do Not Sell My Personal Information
│             </a>
│         </div>
│     </div>
│     
│ </body>
│ </html>
│ 
│ 
│   with module.f5xc_aws_cloud_ce_three_node_multi_nic_new_vpc_new_subnet.volterra_token.site,
│   on ../../modules/f5xc/ce/aws/main.tf line 1, in resource "volterra_token" "site":
│    1: resource "volterra_token" "site" {

**Comment by cklewar** [comment]
seems to be related to HTTP redirect and not a TF issue.
