### ISSUE TITLE
Primary Disk Size Definition

### ISSUE THREAD

**Issue by Mikej81** [f5devcentral/terraform-xc-aws-ce#7]
Field recommended disk min size is 80g.  Currently it is not available to set via variables and using default 40g default.

Could specify in root_block_device for aws provider, or az_nodes{ disk_size{} } in xc provider.

**Comment by cklewar** [comment]
@Mikej81 exposed "aws_instance_disk_size" and set default to 80G.

**Comment by Mikej81** [comment]
Thanks!
